
* shareholder notices
* Issue of New Securities: workflow
** the directors decide that the company needs more money.
** the directors have a board meeting.
*** they pass a resolution that they should issue new equity or debt.
*** the directors call a shareholders meeting -- an EGM.
** the shareholders receive notice of an extraordinary general meeting.
*** unless it happens that the annual general resolution happens to be coming up.
*** the agenda says that the company wants to raise more money.
** the shareholders meet at the EGM and vote on an ordinary resolution to raise more money.

40. The company may from time to time by ordinary resolution do one or more of the following:
a) increase the share capital by such sum as the resolution shall prescribe;
b) consolidate and divide all or any of its share capital;
c) subdivide its shares or any of them, so however that in the subdivision the proportion between the amount paid and the amount,if any unpaid on each reduced share shall be the same as it was in the case of the share from which the reduced share is derived;
d) cancel the number of shares which at the date of the passing of the resolution in that behalf have not been taken or agreed to be taken by any person or which have been forfeited and diminish the amount of its share capital by the number of the shares so cancelled.
41. Subject to any direction to the contrary that may be given by the company in general meeting, all new shares shall, before issue, be offered to such persons as at the date of the offer are entitled to receive notices from the company of general meetings in proportion, as nearly as the circumstances admit, to the amount of the existing shares to which they are entitled. The offer shall be made by notice specifying the number of shares offered, and limiting a time within which the offer, if not accepted, will be deemed to be declined, and, after the expiration of that time, or on the receipt of an intimation from the person to whom the offer is made that he declines to accept the shares offered, the directors may dispose of those shares in such manner as they think most beneficial to the company. The directors may likewise so dispose of any new shares which (by reason of the ratio which the new shares bear to shares held by persons entitled to an offer of new shares) cannot, in the opinion of the directors, be conveniently offered under this regulation.

** the shareholders authorize the directors to issue more shares or debt per the directors' recommendation.
** the directors produce a term sheet showing the shareholders what the raise will look like and what the shareholders' participation should be.
** they send the shareholders a notice.
** the shareholders respond saying whether they want to
1. take the full entitlement
2. take part of the entitlement
3. take more than their share (in case other people took less)
4. decline the entitlement and get diluted
** then the directors spend some time in excel figuring out how to square it all. the term "pro rata" comes up a lot. things are always divided according to relative shareholding proportions.
** you send out to all the shareholders, existing and proposed ones, a cap table of the company showing before and after the fundraising
** then the lead investor negotiates a bunch of paperwork
*** if a shareholder agreement doesn't already exist,
**** then a shareholder agreement
**** else a deed of ratification and accession
*** investor rights agreement (sometimes)
*** subscription agreement
* useful links
http://www.reportally.com/
http://captable.io/
http://termsheet.io/
http://legalese.com/
http://updatemyvc.com/






