media:
  input: public/assets
  output: /assets
  categories: [ "image" ]
content:
  - name: posts
    label: Blog Posts
    type: collection
    path: _posts
    view:
      fields: [ coverImage, title, date, published ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: published, label: Published, type: boolean, default: false }
      - { name: excerpt, label: Excerpt, type: string, required: true }
      - { name: coverImage, label: Cover image, type: image, required: true }
      - { name: date, label: Date, type: date, options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" } }
      - name: author
        label: Author
        type: object
        fields:
          - { name: name, label: Name, type: string, required: true }
          - { name: picture, label: Picture, type: image, required: true }
      - name: ogImage
        label: Image (social sharing)
        type: object
        fields:
          - { name: url, label: URL, type: image, required: true }
      - { name: body, label: Body, type: rich-text, required: true }

  - name: pages
    label: Pages
    type: collection
    path: _pages
    view:
      fields: [ title, slug, showInHeader, footerColumn ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: slug, label: Slug, type: string, required: true }
      - { name: navTitle, label: Navigation Title, type: string, description: "Title to display in navigation (uses page title if empty)" }
      - { name: showInHeader, label: Show in Header Menu, type: boolean, default: false }
      - { name: headerOrder, label: Menu Order, type: number, description: "Order in header navigation (lower = first)" }
      - name: footerColumn
        label: Footer Column
        type: string
        options:
          values: [ "company", "resources", "contact", "legal", "none" ]
        default: "none"
        description: "Which footer column to show this page in (company, resources, contact, legal, none)"
      - { name: footerOrder, label: Footer Order, type: number, description: "Order within footer column (lower = first)" }
      - { name: lastModified, label: Last Modified, type: date }
      - { name: effectiveDate, label: Effective Date, type: date }
      - { name: body, label: Content, type: rich-text }
  - name: external_links
    label: External Links
    type: collection
    path: _external_links
    view:
      fields: [ title, url, footerColumn ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: url, label: URL, type: string, required: true }
      - name: footerColumn
        label: Footer Column
        type: string
        options:
          values: [ "company", "resources", "contact", "legal", "none" ]
        required: true
        description: "Which footer column to show this link in (company, resources, contact, legal, none)"
      - { name: order, label: Order, type: number, description: "Order within footer column (lower = first)" }
      - { name: description, label: Description, type: string }