#+TITLE: Events

* 2016-03-21 to 2016-03-25 Legalese Summit, Singapore
immediately following FOSSAsia -- see [[*2016-03-18 to 2016-03-20: FOSSAsia, Singapore][below]].

** Goals
Establish customer empathy for the early adopter segment -- the non-US founder of a tech startup raising funding or setting up an ESOP.

Plan out critical path toward business success:
- web app product development
- funding either public or private
- research project: expressive language required for efficient support for international jurisdictions
- opensource rollout for both the code and the legals
- marginally profitable revenue collection
- for scale, all human interactions to be referred out to legal or consultant partners

We will answer these questions:
- Who else is working in this domain?
- Why haven't they succeeded yet?
- How long will this take?
- What kind of organization do we need to build?
- What resources do we need to acquire?
- What deadlines?
- What conferences, if any, shall we attend?
- What core competitive advantage does the Legalese project have?

For each project participant, we evaluate:
- What level of commitment and contribution can we expect over the next 12 months?
- What level of compensation will be required to deliver that commitment?

** Format
Five days of afternoon sessions.

Each afternoon we hold two sessions.

Each session is two to three hours. Presentation, then discussion, then consensus.

** Food
*** CANCELLED newton stingray from stall 39
*** DONE master crab chili crab
*** DONE warong nasi pariaman
*** DONE wee nam kee chicken rice
*** TODO bak kut teh
*** TODO dim sum in geylang? 126
*** TODO indian fishhead curry
*** TODO roti paratha
*** TODO ya kun teatime

** Agenda
*** Day 1A: 30,000 foot introduction to the project for the absolute n00b.
**** introduction to the customer segment and use cases.
invite guest in, together with any other users, to talk about why they found it useful.

guest will come at 10am monday morning to our resort venue.

**** positioning, differentiation, and competitive advantage
**** how this makes a difference to the world
**** why meng is excited about it
history with SPF
**** why lots of other people seem to be excited about it
**** introductions over breakfast
customers: martin from ncinga, wobe
**** 10-year future vision
**** interaction with trendy topics like smart contracts
**** the presentations i've been giving
**** a brief history of legal informatics
minefields and milestones
*** Day 1B: meet the incumbent industry
**** How do lawyers work?
**** How are contracts drafted?
**** How are contracts negotiated?
counterparty offers feedback, you reject half of it
**** Defined Terms
inline or up front?

functional evaluation -- looking things up, six bookmarks deep
**** Clause Banks
when you leave, you leave with you
**** Precedent Libraries
different teams don't share.
**** What do Lawyers actually do for clients?
***** negotiation
***** education
***** drafting of the primary agreements
***** drafting of the ancillary paperwork like resolutions
***** drafting of letters, e.g. a notice template
***** getting the commissioner uncles to come and sign things
***** execution management
*** Day 2A: Organization
**** the organization of the project as both opensource and startup.
***** participation model.
***** IETF, opensource values
rough consensus and running code.

***** participants' expectations of the project
***** the project's expectations of participants
***** transparency by default; online archive is authoritative
what to do about confidential information?
***** funding. compensation.
[[http://www.holacracy.org/wp-content/uploads/2015/08/Badge-basedCompensationApp-v1.0.pdf][badge-based compensation]].
***** holacracy.
**** minutes https://guides.github.com/features/issues/

a new contributor's guide.

start with a readme file. not "come and talk to meng."

then you see a CONTRIBUTING file in the repo somewhere, connected to issues.

mariadb uses jira. worklogs.

let's consider using https://gitter.im/ which is more open than slack.

could this be a good project for google summer of code 2017?

http://hackingbusinessmodel.info/

dogfood: get paid to do a pull request.

post-payment = convertible note.

pre-payment = executory contract. because it locks the issue to you and others can't work on it.

https://github.com/cbas/lgtm

*** Day 2B: Research -- Business
so we want to disrupt the incumbents.

let's look at the state of the art -- what other people are thinking.

**** competitor analysis
Is this even a good idea at all?
http://feld.com/archives/2010/04/failing-fast-at-standardized-seed-deal-documents.html

different families of approaches:

A brief pictorial overview https://drive.google.com/open?id=0BzJyMUr3UozTNTZvT3BJMHZUUVk

A more detailed look at the landscape including whether founders has law and CS training https://docs.google.com/spreadsheets/d/1UJzUk_ejxUioU276Da8dSebEF7vJFAi1_Yw1_vxSRGE/edit#gid=0

***** NLP -- reading existing contracts.
***** helping with litigation
***** helping with research
***** helping with paperwork
***** helping with execution and signatures
***** datarooms
***** other players
***** DONE what stanford is up to
***** commonaccord
***** ethereum

**** Lean Startup findings to date
***** who's the customer?
***** and the rest of the lean canvas

**** Wardley mapping of the legal informatics field
why we're in the right place at the right time.
**** how will this become a billion-dollar business?
the MySQL / MariaDB story

*** Day 3A: Research -- Technical
**** overview of technology architecture, components, and backlog.
**** roadmap overview: present and future
**** working through an actual use case of the current product
pretend you're a founder raising funding. put everyone in the shoes of the early adopter.

first, use it as a user.

then, install a dev environment and get set up as a developer.

overview of the issues list in github
**** a longer review of prior art.
**** areas of research required. the future product. interaction with IHLs and RIs.
**** maturing areas and projections over the next few years.

*** Day 3B: Product Overview

**** minutes

should we build a DSL for smart contracts, or a DSL for contracts?



*** Day 4A: more work

**** current status of running code and working, supported use cases.
**** a laundry list of technologies involved in the current product
is there any way to shorten the ingredient list?
**** product roadmap. MVP. inclusion and exclusion.
plans for the next 6, 12, 24 months.
**** rough task allocation of issues in git.
**** go/no-go milestones for the next 12 months
in terms of marketing, revenue, and funding.





*** Day 4A: practice with the workgroup tools
practice with issue creation and task allocation.

what do we do about simultaneous allocation?

practice with communication tools

practice with holacracy circles

practice with interacting with the outside world. porous boundaries.

What does and doesn't require permission from others?

What should and shouldn't require notifications to others?
*** Day 4 lunch: special guest: crowdfunding site to explain their requirements
*** Day 4B: Concrete Plan for What Will Happen in 2016

In which everybody gets on to The Same Page.

**** What does Legalese look like at the end of May 2016?

Legalese v1.0 is the current Google Docs app.

With the six critical issues resolved, that makes it usable by a determined end-user, it becomes version 1.2.

Legalese v2.0 has a much nicer skin and front-end with defaults that pre-fills and wraps the v1.0 spreadsheets.

v2.0 handles, for any Singapore startup,
- incorporation
- NDAs / confidentiality
- ESOP
- adding a co-founder
- employment agreements
- volunteer agreements
- seed fundraising round

v2.0 includes unit tests to verify each of these workflows.

We have a simpler front-end that encapsulates the spreadsheet tier.

We charge money for the premium version of the basic product.

IP and CLA sorted out.

**** What does Legalese look like at the end of Dec 2016?

Legalese v3.0 has a working, very simple, DSL to English compiler, with some ugly hardcoded crap in there.

We have expressed at least three seed investment agreements in the DSL.

The three seed investment agreements compile to working templates.

Those working templates are available for actual use by the v1.0 system.

The DSL compiler can handle
- inter-document references and definitions
- to english
- to something other than english

***** Interaction with third party service integrators and value added vendors. Target: September 2016.
The DSL is usable by a law firm to build its own proprietary templates. It can build the agreements, or we might support a third party consultant who wants to help the law firm build the agreements, but we would prefer not to be supporting the law firm directly on a consulting/services model.

We could define the codebase is noncommercial; if you want to use this for white-label purposes, or get support, we will negotiate a licensing fee. Inspirations: apple app store; hosted wordpress with a theme marketplace. Charge each time the thing is used in production, e.g. Neota Logic.

Legalese could then make money on hosting the front-end and charging third party vendors to be on the marketplace.

**** Business Milestones

***** By the end of 2016,
we shall have sold at least one workflow to a startup which may be JFDI or non-JFDI.

Prove the direct sale model to see if martin is willing to pay for the current work.

Charge for conversion of agreements to XML. Train staff to do that.

***** Sometime around August 2016,
develop workflows and XML templates for AU startups. Launch to some AU startups. See if AU startups will pay. Possible docs include http://www.startmate.com.au/financing-docs


**** What does Legalese look like at the end of 2017?

***** Version 4.0 has a more sophisticated working DSL that supports Natural Language Generation.

To get from v3 to v4, the IP-heavy product development R&D will be built with the assistance of academia.

We will output to English.

***** Monetization at scale will also happen in v4!

***** Compilation to Ethereum and/or Hyperledger

need an R&D team on this.

***** v4.7: Support for maintained fork/branches

In the course of a single deal, during negotiations, deltas will appear from the counterparty; maintain a parallel branch that applies those deltas, at the text/string level, to that deal's paper, even while the master branch templates continue to update.

But it would be even cooler if lawyers could submit patches in the high-level DSL.

**** What about English to Legalese?

After 2017, we will decide if we want to have:

v5.0: round-trip isomorphism from reading English and turning it into the DSL. If the government offers us $50M in funding to do a LegalTech Research institute and they want Computational Linguistics to be a component, and they want to know how we will spend the money, we will say that some of it will be spent on this.

Data61 has already done a bit of that.

Hack the above using simulated annealing in the opposite direction.

**** Who's going to do what? What approximate range of commitments might each person be able to indicate?

Each of the following is a *circle* containing multiple *roles* filled by one or more *people*.

Each circle gets its own Slack channel.

- v1 XML template Import and Maintenance :: Meng and Jobchong as primary support. Alexis to review all the existing templates to see if they are fit for purpose in SG. Add docs as needed to support the M@C Test Case.
- v1 backend support :: Meng and Anuj
- v2 Web Front End UI Circle :: Sebastiaan plus designer. We need a pixel pusher. Has in mind a girl he found in a school somewhere. The last girl went off to the north pole. Maybe this one will flee to Antarctica. Please try to find one who will stay in the tropics. User experience will be advised by Alexis. Anuj also involved in devops?
- v3 DSL R&D :: Michal, Long, Meng, Yochi, Chiah Li, Anuj will act in a variety of roles: designer, compiler author, test user. This includes DSL to English ontology and natural language blobs. Conversion of The JB Test Case into formalism.
- v3E DSL R&D :: Compilation to Ethereum. Anuj & Virgil (on tech), Yochi (on market research and customer demand).
- Evangelist and External Interface :: Virgil and Meng.
- Interfacing with Academia in Singapore :: Virgil and Meng
- Interfacing with Academia in Australia :: Yochi to explore and send out feelers
- Inbound Marketing and Blogging :: Meng would like any content we produce to be original && true && useful. Yochi to write a white paper for a law journal about how DSLs may change the world.
- Business Team to position, brand, and strategerize the product :: customer discovery to lead all the rest. Wardley mapping, the competitor analysis, keeping track of other projects.
- Compensation Committee :: to design the pre- and post-funding credit algos. negotiate each person's compensation. #finance. Who will be on this?
  - suggested: Chiah Li
  - accepted: Virgil
  - accepted: Meng
  - sebastiaan suggests asking the Buffer Girl to come on and help architect it.
  - 

- Investment Team to herd the cats toward a close :: Lev.B.Man to levitate in and be the Closer while everybody else waits outside with empty coffee cups. Virgil, meng, Alexis knows rich lawyers, Chiahli knows rich people.

Each circle above should have a lead link and should have its own slack chat.


**** Is fundraising going to happen?

We plan to raise S$2M by the end of 2016.

$2M will help us run for 18 months.

S$5.48--8M pre.

$1M of angel money, 250k * 4/5, from SG, AU, US

$1M of institutional seed / VC money, maybe US, UK.

$1M of matching government money on CRP/IAF or SPRING TECS POV -- on reimbursement basis, so not really real.



**** How are we going to pay whom?

ESOP will probably be 15%

But let's try a more enlightened, 21st century, holacratic style approach to compensation involving bounty ideas, badge-based compensation, stack ranking, Valve, Buffer, Stripe, transparency.

We can also let people balance their cash vs equity split each month.

Everybody should be sufficiently compensated & appreciated to continue working on the project.

***** Before we get funded

We can offer convertible debt plus a convertible sofa in Venice.

People who can work on those terms -- and they don't have to work full-time -- can be compensated in the same ways as everybody else.

We might be able to offer a very small cash drip.

Prior to the big funding round we can do a small funding round from other members of the company.

There will be different mechanisms to issue credit for work done. We could issue "Monopoly money" credit, which then converts to cash/notes/equity. Some algo will be involved here.

***** After we get funded

Each contributor can choose their cash/equity split each month. There will be some algo around this.



**** Do we implement Holacracy now? Or what else do we do?

Let's all read the book(s) on that stuff, or get our SOs to read the book and explain to us what it all meant.

Also Valve handbook.

**** Must we all read all the books!?

Alexis to canonicalize the books and communicate the full set and have her be in charge of making sure everybody is indoctrinated.

**** Is everyone fully onboarded?

Everybody needs to be on
1. Google Drive
2. Slack
3. active-team@legalese.io
4. Github

Who will be in charge of onboarding and reboarding everyone? Alexis.

**** How do we represent the project/company to other people?

Everyone is empowered to be the public face of the company, but in delicate situation are advised to caveat that not everybody else in the company might agree and they can't commit the company/project to do stuff.

Also, inform the rest of the company that you like talked to whomever, so that we don't appear totally frazzlebrained. This is called "CRM".

So before you interact with anyone, just search for their name across:
- Slack
- Google Drive
- Github

And if we have had any interaction with them in the past the search should return a result.

We are not organized enough to enforce CRM discipline.

**** Do we need to bring on other people? Is it possible to use freelancer sites?

UI designers.

**** What do we do about proposed partnerships / relationships?

Don't commit anyone else to work that they haven't agreed to.

**** What do we do when people want to volunteer?

Volunteers are welcome, but we need a mechanism to gracefully mute non-contributing volunteers. Badge-based compensation will help with this.


*** Day 5A: Progress.
Make something useful, or independent activity

Perform follow-ups, emails, start executing action items from the week

invite special guest that we can summarize to; get opinion, hear what they think.

friendly VC to explain what metrics they would want to see from us before investing.

**** minutes [2016-03-25 Fri 16:38]

to make our language more useful around version 3 or 4, we have to tag our functions as ones which are performable in the smart contracts world vs those which are performable in meatspace.

can't we discriminate actors which are online vs offline; the ones which are online are first-class agents.

one perspective: courts would think about this in terms of damages. if a court can order specific performance, it is a meatspace action.

smart contract needs a way to know what has happened in meatspace. the event log (and related things like ipfs)

multisig supports jointly appointed independent verifier.

#lawdev has the details.




*** Day 5B: relax.
afternoon off, let's go to sentosa. calamari at tanjung beach club.

then marina barrage to see skyline.

** Fees
free. Some financial assistance may be available for interns/students/etc.
** Registration
To register for the summit: submit a pull request that edits this document.
** Attendees
sorted by alpha, please
*** In-Person
- alexis
- byte (Colin Charles) for first 2 days?
- jobchong
- mengwong
- oatsandsugar
- anuj
- advancingdragon
- virgil?
*** Online
- Chiah Li
- Daniela

* 2016-03-18 to 2016-03-20: FOSSAsia, Singapore
Meng will present Legalese in one of the conference sessions.

http://2016.fossasia.org/

** Content
1. use of opensource in legalese. gripes about academic prior art not being opensource.
2. legalese itself being opensource, and comparisons to other infrastructure pieces like mysql/mariadb; the demographic of the opensource contributor as being both a user and a developer of the software, often as an adjunct to the day job
3. legalese being a facilitator of "smart contracts" and contracts generally that are themselves opensource – blurring the line between creative commons and opensource content.
4. some amusing remarks questioning who owns the copyright in a contract
5. the situation with precedents is a lot like the state of software before opensource

the inspiring theme here, perhaps, is that humans are the only animal to use language as a tool. this interpretation of humanity elevates poets, lawyers, and programmers.

working backward from this agenda, what could the MVP for the purposes of fossasia look like? it could, very primitively, support the expression of a contract in our DSL, which converts to english and to ethereum. that expression of the contract should be opensourced, in a way that definitively addresses some of the unknowns highlighted in http://www.adamsdrafting.com/downloads/Copyright-NYLJ-8.23.06.pdf

