#+TITLE: Events

* 2016-03-21 to 2016-03-25 Legalese Summit, Spring 2016, Singapore
immediately following FOSSAsia -- see [[*2016-03-18 to 2016-03-20: FOSSAsia, Singapore][below]].

** Goals
Establish customer empathy for the early adopter segment -- the non-US founder of a tech startup raising funding or setting up an ESOP.

Plan out critical path toward business success:
- web app product development
- funding either public or private
- research project: expressive language required for efficient support for international jurisdictions
- opensource rollout for both the code and the legals
- marginally profitable revenue collection
- for scale, all human interactions to be referred out to legal or consultant partners

We will answer these questions:
- Who else is working in this domain?
- Why haven't they succeeded yet?
- How long will this take?
- What kind of organization do we need to build?
- What resources do we need to acquire?
- What deadlines?
- What conferences, if any, shall we attend?
- What core competitive advantage does the Legalese project have?

For each project participant, we evaluate:
- What level of commitment and contribution can we expect over the next 12 months?
- What level of compensation will be required to deliver that commitment?

** Format
Five days of afternoon sessions.

Each afternoon we hold two sessions.

Each session is two to three hours. Presentation, then discussion, then consensus.

** Food
wee nam kee chicken rice

bak kut teh

indian fishhead curry

warong nasi pariaman

eng seng pepper crab

dim sum in geylang? 126

newton stingray from stall 39

roti paratha

ya kun teatime

** Agenda
*** Day 1A: 30,000 foot introduction to the project for the absolute n00b.
**** introduction to the customer segment and use cases.
invite Wobe in, together with any other users, to talk about why they found it useful.
**** positioning, differentiation, and competitive advantage
**** how this makes a difference to the world
**** introductions over breakfast
**** 10-year future vision
**** interaction with trendy topics like smart contracts
**** the presentations i've been giving
**** a brief history of legal informatics
minefields and milestones
*** Day 1B: meet the incumbent industry
**** How do lawyers work?
**** How are contracts drafted?
**** How are contracts negotiated?
counterparty offers feedback, you reject half of it
**** Defined Terms
inline or up front?

functional evaluation -- looking things up, six bookmarks deep
**** Clause Banks
when you leave, you leave with you
**** Precedent Libraries
different teams don't share.
**** What do Lawyers actually do for clients?
***** negotiation
***** education
***** drafting of the primary agreements
***** drafting of the ancillary paperwork like resolutions
***** drafting of letters, e.g. a notice template
***** getting the commissioner uncles to come and sign things
***** execution management
*** Day 2A: Research -- Business
so we want to disrupt the incumbents.

let's look at the state of the art -- what other people are thinking.

**** competitor analysis
Is this even a good idea at all?
http://feld.com/archives/2010/04/failing-fast-at-standardized-seed-deal-documents.html

different families of approaches:

***** NLP -- reading existing contracts.
***** helping with litigation
***** helping with research
***** helping with paperwork
***** helping with execution and signatures
***** datarooms
***** other players
***** what stanford is up to
***** commonaccord
***** ethereum

**** Lean Startup findings to date
***** who's the customer?
***** and the rest of the lean canvas

**** Wardley mapping of the legal informatics field
why we're in the right place at the right time.
**** how will this become a billion-dollar business?
the MySQL / MariaDB story

*** Day 2B: Research -- Technical
**** overview of technology architecture, components, and backlog.
**** roadmap overview: present and future
**** working through an actual use case of the current product
pretend you're a founder raising funding. put everyone in the shoes of the early adopter.

first, use it as a user.

then, install a dev environment and get set up as a developer.

overview of the issues list in github
**** a longer review of prior art.
**** areas of research required. the future product. interaction with IHLs and RIs.
**** maturing areas and projections over the next few years.
*** Day 3A: Organization
**** the organization of the project as both opensource and startup.
***** participation model.
***** IETF, opensource values
rough consensus and running code.

***** participants' expectations of the project
***** the project's expectations of participants
***** transparency by default; online archive is authoritative
what to do about confidential information?
***** funding. compensation.
[[http://www.holacracy.org/wp-content/uploads/2015/08/Badge-basedCompensationApp-v1.0.pdf][badge-based compensation]].
***** holacracy.
*** Day 3B: practice with the workgroup tools
practice with issue creation and task allocation.

what do we do about simultaneous allocation?

practice with communication tools

practice with holacracy circles

practice with interacting with the outside world. porous boundaries.

What does and doesn't require permission from others?

What should and shouldn't require notifications to others?

*** Day 4A: Product Overview
**** current status of running code and working, supported use cases.
**** a laundry list of technologies involved in the current product
is there any way to shorten the ingredient list?
**** product roadmap. MVP. inclusion and exclusion.
plans for the next 6, 12, 24 months.
**** rough task allocation of issues in git.
**** go/no-go milestones for the next 12 months
in terms of marketing, revenue, and funding.
*** Day 4 lunch: special guest: crowdfunding site to explain their requirements
*** Day 4B: Product Development
let's build something together
*** Day 5A: Progress.
Make something useful, or independent activity

Perform follow-ups, emails, start executing action items from the week

invite special guest that we can summarize to; get opinion, hear what they think.

friendly VC to explain what metrics they would want to see from us before investing.

*** Day 5B: relax.
afternoon off, let's go to sentosa. calamari at tanjung beach club.

then marina barrage to see skyline.

** Fees
free. Some financial assistance may be available for interns/students/etc.
** Registration
To register for the summit: submit a pull request that edits this document.
** Attendees
sorted by alpha, please
*** In-Person
- alexis
- byte (Colin Charles) for first 2 days?
- jobchong
- mengwong
- oatsandsugar
- anuj
- advancingdragon
- virgil?
*** Online
- Chiah Li
- Daniela

* 2016-03-18 to 2016-03-20: FOSSAsia, Singapore
Meng will present Legalese in one of the conference sessions.

http://2016.fossasia.org/

** Content
1. use of opensource in legalese. gripes about academic prior art not being opensource.
2. legalese itself being opensource, and comparisons to other infrastructure pieces like mysql/mariadb; the demographic of the opensource contributor as being both a user and a developer of the software, often as an adjunct to the day job
3. legalese being a facilitator of "smart contracts" and contracts generally that are themselves opensource – blurring the line between creative commons and opensource content.
4. some amusing remarks questioning who owns the copyright in a contract
5. the situation with precedents is a lot like the state of software before opensource

the inspiring theme here, perhaps, is that humans are the only animal to use language as a tool. this interpretation of humanity elevates poets, lawyers, and programmers.

working backward from this agenda, what could the MVP for the purposes of fossasia look like? it could, very primitively, support the expression of a contract in our DSL, which converts to english and to ethereum. that expression of the contract should be opensourced, in a way that definitively addresses some of the unknowns highlighted in http://www.adamsdrafting.com/downloads/Copyright-NYLJ-8.23.06.pdf

