#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="file://localhost/Users/admin/Sites/org-style.css" />

* visualisation of contracts

To turn text-heavy contracts into graphics. Soving a most challenging problem in making contracts understandable to ordinary people. 

** Possible tools

1.  Astor plot D3.js
2.  Tableau


* First we have to code up a comparable economic and control provisions of all the contract templates.

work-in-progress googlesheet here 
https://docs.google.com/spreadsheets/d/1eQd-eFdfOkT6w37_s-JHPGPN5xDmMNoXh0k1YMxJ3Q8/edit#gid=0

i am guessing some input variablesNUm would be needed, otherwise how to show the strength of each arc.

** 20150612 update:
Encountering some difficulties in the thinking process. How to represent terms that are very specific to each type of contract. Using 500 KISS (debt) as an example, it has very specific treatment on a major investment right clause: "Condition: Investor has invested at least 50k. 
1.  Information rights, and 
2.  Participation rights of 1x the original investment." 

How to represent that in a variableNum format? This is quite unlike frogscore where there is a score of 1-10 for a specific question...

Hmm..

The solution could be:
1. that the major investor slice be hightlighted and user seeing that slice is highlighted can then manually check out that clause in the contract itself.
2. perhaps check out circos?

** 20150615 update:

The commonality for the clauses falls into either ownership on exit or control over the board === voting rights. Will start with these two premise.

* Then, we suck everything out of the googlesheet



* To output chart variables

Likely that the svg outputter relies on certain variables.

Results would be:
1. 500 KISS equity.svg
2. 500 KISS debt.svg
3. YC SAFE discount cap.svg
4. YC SAFE discount.svg
5. YC SAFE cap.svg
6. YC SAFE MFN.svg

etc etc

** 20150615 update:
Outputting a svg for each template does not represent the soul of the agreement. It would be far better to output a svg based on the input parameters of ownership on exit and voting rights as this will enable user to make an informed decision on the implications of the contracts.


