* Sysadmin Notes
The www.legalese.io website is served via Github Pages.

The repository is legalese-io/legalese-io.github.io.

Meng has an account with the DNS provider iwantmyname.com.

The DNS provider configures a CNAME record for legalese.io pointing to legalese-io.github.io.

https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

The DNS provider also configures A records pointing to Google.
https://admin.google.com/AdminHome#Domains:

The rest of legalese.io -- everything besides the website -- is hosted by Google. That mostly means Gmail.

At Google, legalese.io is configured to redirect to www.legalese.io.
* User Categories
** Signers
The people who actually execute the agreements just see documents coming at them via an e-signing service like EchoSign or DocuSign.

They don't have to know that Legalese exists at all, except possibly for the watermark and branding that decorates the cover pages.

They might fill in a Google Form generated by Legalese but that's about it.

** Business Users

Business users set up Document Sets using Legalese and generate agreements for signers to sign.

Business users populate the spreadsheets with the particulars of the parties and the terms of the agreements.

The user-facing interface lets business users enter details into Google Spreadsheets. Legalese reads those spreadsheets and creates PDFs.

Sometimes the business users are the signers -- on one side of the transaction.

The business users are responsible for reminding the signers to sign.

** Drafters

Contract drafters modify existing agreements and create new ones.

Docracy has a beautiful UI for forking and editing docs online.

Legalese doesn't even have a UI: our templates are kept in XML and drafters need to be comfortable editing XML. Drafters need to learn how to work with Github and edit XML files.

Sometimes an advanced business user will take the lead in drafting new content for Legalese, or for adapting existing agreement for their purposes.

Drafters are either domain experts -- lawyers and business people -- or junior staff reformatting existing third party templates into Legalese.

Drafters don't need to be coders. They do need to undergo a bit of training, to:
- learn how to use git and Github
- learn how to edit Legalese XML
- learn how to 

** Coders
Software developers hack the deep technical bits that support the above three user categories interfaces.

** Ratios
Roughly speaking ...

For every ten signatories there is one business user.

For every ten business users there is one drafter.

For every ten drafters there is one coder.

* The Legalese XML Format

Legalese XML isn't that different from HTML. We have some of the same ideas, like <i> for italics and <b> for bold.

We do use different tags for paragraphs -- <numbered_1_para> and <numbered_2_para> for instance. Numbered paragraphs, basically, prefixed with (N.) and (N.N.) respectively.

Legalese XML isn't that different from PHP. It supports <?=variable?> and <?logic?> tags.

You use those special tags to include or exclude words, sentences, or paragraphs depending on the terms and configuration of the agreement.

Thanks to these tags, Legalese offers easy ways to pluralize words: for example, <?=plural(data.parties.investor,"Investor")?> counts the number of investors and inserts the word "Investor" or "Investors" as appropriate.

* outcome visualization
like a choose-your-own-adventure -- show the longitudinal study on what happened to people in whatever situation who went with whatever combination of options.

a tree structure, showing which paths have been least explored.

* mascot

** orca
because they drag sharks upside down for amusement until they die, and eat their livers
