#+TITLE: Documentation for the Class F Agreement

Founder vesting is implemented using Class F shares. The class definitions are found in the company constitution. Instance attributes are configured in the Class F Agreement.

* Introduction to Vesting
Why does vesting matter, and what are some of the conventions that have arisen?

Much has been written on the subject. We won't repeat that here. [[https://www.google.com/search?q=startup+vesting+guide][Google is your friend]].

There are two specific resources you should read:
- [[https://dl.dropboxusercontent.com/u/9544489/class%2520f%2520frog%2520vesting.pdf][How the Frogs Invented Vesting]]
- [[http://venturehacks.com/articles/option-pool-shuffle][Option Pool Shuffle]]

* By Jurisdiction

** Singapore

In Singapore, IRAS has [[https://www.iras.gov.sg/IRASHome/Individuals/Foreigners/Working-out-your-taxes/What-is-Taxable-What-is-Not/Stock-Options/][a page on the tax treatment of stock options]].

The JFDI template currently supports Singapore jurisdiction.

*** Alternative Structures for Redemption

There are many ways to set up a vesting scheme. Why did JFDI choose this particular point in the space of possibilities?

**** Actual Shares vs Phantom Stock

JFDI decided against [[http://www.forbes.com/sites/dking/2013/10/15/why-phantom-stock-can-be-better-than-real-stock/][Stock Appreciation Rights and Phantom Stock]]. Why? Because JFDI understood that in Singapore, the capital gains of shares are not taxed, whereas cash payouts under an SAR or Phantom scheme would be taxed as income.

So, actual shares.

**** Repurchase of Shares

When a founder departs, what happens to their shares? Either they get repurchased by the company, or they get repurchased by the other shareholders.

***** Repurchase by the Other Shareholders

If the shares are repurchased by the other shareholders:
1. Stamp duty would be involved in the transfer of shares.
2. Shareholders would need to actively elect to purchase the shares. A shareholder who was incommunicado or not paying attention would be adversely affected.
3. The repurchase rights would need to be recorded in the shareholders' agreement, so that new shareholders who became members of the company subsequent to the establishment of the Class F Agreement would enjoy the same purchase rights.
4. The purchase price of the shares would need to be determined. Should it be a nominal low value of $0.0001 per share? Or last market rate? Would the purchase price differ based on the buy-in price of each shareholder? The setting of such a purchase price might have unintended consequences, such as inadvertently fixing a "market rate" as a reference for some future transaction.

Therefore, repurchase by the company is the superior alternative.

***** Repurchase by the Company
If the shares are repurchased by the company, [[http://statutes.agc.gov.sg/aol/search/display/view.w3p;ident=0036f0ee-17e5-4af1-81a2-335a970659f5,39eedd77-96e3-402b-9f0c-23424a9b8ce7,aefee39e-5ed0-44e9-9077-5156e5c214a5,d08cbcd0-f97e-4e67-b5fc-6561e031309e;page=0;query=DocId%253Ac3063e4b-61ed-4faf-8014-fabd5b998ed7%2520Depth%253A0%2520Status%253Ainforce;rec=0][regulation 76B]] applies: 76B(3) imposes a 20% limit on the repurchase of ordinary shares and stocks in any class.

**** Ordinary Shares or Preference Shares?

That means that if the vesting scheme were implemented using ordinary shares, then if a one-third founder were to depart, repurchase of 33% of shares would exceed the 20% limit.

But 76B(3D) creates an exception: /there shall be no limit on the number of redeemable preference shares that may be purchased or acquired by a company during the relevant period./

So, we define Class F shares as redeemable preference shares.

**** Treasury or Cancellation?
If the shares are repurchased by the company, the company can hold the shares as treasury, or cancel the shares.

Regulation [[http://statutes.agc.gov.sg/aol/search/display/view.w3p;ident=babfd94a-c3e6-4fde-8025-a1b60c4e0ad3,ad495ceb-10f1-4194-97e6-38d33c8146c9;page=0;query=DocId%253Ac3063e4b-61ed-4faf-8014-fabd5b998ed7%2520Depth%253A0%2520Status%253Ainforce;rec=0][76I]] does not allow more than 10% of a company's shares to be held as Treasury.

So, once founder shares are redeemed by the company, they are immediately cancelled. This is true for the physical shares.

However, the directors have the latitude to assign the cancelled shares to the ESOP pool, which is a logical construct. The assumption is that the departure of the founder leaves a hole which will eventually be filled by new hires, and those new hires will demand shares of approximately the same size as the hole. So, if 10,000 shares are redeemed and cancelled, then the ESOP pool grows by 10,000 shares.

*** F Shares as Solution to Constraints
Given the above constraints, the JFDI standard vesting scheme defines Class F shares, which are redeemable preference shares, which upon departure of a founder are redeemed out of capital and then cancelled.

** US

In the US, you need to know about an [[http://acceleratedvesting.com/what-is-an-83b-election-and-when-do-i-make-it-part-1-with-graphic/][83(b) Election]].


